name: bicom
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # provider
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  # tts
  flutter_tts: ^3.6.3
  # local database
  shared_preferences: ^2.1.0
  url_launcher: ^6.2.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_native_splash: ^2.0.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true